# Qwen2.5-3B generalist model - Deep verbose experiment
experiment_name: "qwen3b_verbose_deep"
seed: 42

model:
  name: "Qwen/Qwen2.5-3B-Instruct"
  max_new_tokens: 2048  # High limit for deep chains + verbose explanations
  temperature: 0.0
  model_kwargs:
    device_map: "mps"

data:
  generator: "arith"
  n_instances: 15       # Same as terse for comparison
  max_depth: 25         # Same depth to test redundancy hypothesis
  condition: "verbose"
  initial_value: 1

logging:
  out_dir: "results/synthetic"
  level: "INFO"

analysis:
  survival:
    time_axes: ["step", "tokens_total"]
    curves: ["km"]