# Smaller Qwen terse test to verify the fixes work
experiment_name: "qwen_terse_small"
seed: 42

model:
  name: "Qwen/Qwen2.5-Math-1.5B"
  max_new_tokens: 1024  # High limit
  temperature: 0.0
  model_kwargs:
    device_map: "mps"

data:
  generator: "arith"
  n_instances: 5        # Small for quick test
  max_depth: 8          # Moderate depth
  condition: "terse"
  initial_value: 1

logging:
  out_dir: "results/synthetic"
  level: "INFO"

analysis:
  survival:
    time_axes: ["step", "tokens_total"]
    curves: ["km"]