# Micro test with Qwen - optimized for local testing
experiment_name: "synthetic_qwen_micro"
seed: 42

model:
  name: "Qwen/Qwen2.5-Math-1.5B"
  max_new_tokens: 128  # Reduced from 256
  temperature: 0.0
  model_kwargs:
    device_map: "mps"  # Use Apple Silicon GPU

data:
  generator: "arith"
  n_instances: 3       # Very small for testing
  max_depth: 5         # Reduced depth
  condition: "terse"
  initial_value: 1

logging:
  out_dir: "results/synthetic"
  level: "INFO"

analysis:
  survival:
    time_axes: ["step", "tokens_total"]
    curves: ["km"]