# Quick test of Qwen2.5-3B generalist model
experiment_name: "qwen3b_quick_test"
seed: 42

model:
  name: "Qwen/Qwen2.5-3B-Instruct"
  max_new_tokens: 1024
  temperature: 0.0
  model_kwargs:
    device_map: "mps"

data:
  generator: "arith"
  n_instances: 3
  max_depth: 6
  condition: "terse"
  initial_value: 1

logging:
  out_dir: "results/synthetic"
  level: "INFO"