# Test synthetic experiment with small parameters
experiment_name: "synthetic_test"
seed: 42

model:
  name: "gpt2"
  max_new_tokens: 128
  temperature: 0.0

data:
  generator: "arith"
  n_instances: 3
  max_depth: 5
  condition: "terse"
  initial_value: 1

logging:
  out_dir: "results/synthetic"
  level: "INFO"

analysis:
  survival:
    time_axes: ["step", "tokens_total"]
    curves: ["km"]